### ISSUE TITLE
error 404 Link dwl language

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/QuestsDoc#11]
Error 404 page no found to the link in the wiki ( https://github.com/PikaMug/Quests/tree/master/main/src/main/resources/lang )

https://pikamug.gitbook.io/quests/casual/translations#troubleshooting
![image](https://user-images.githubusercontent.com/74351200/179371465-a4eb1ed2-0baf-4d13-be6c-5942fb368fd3.png)
![image](https://user-images.githubusercontent.com/74351200/179371594-715a3b9a-8cfa-4407-ba5a-176eca2dbf60.png)

**Comment by PikaMug** [comment]
Thank you, should be resolved.
