### ISSUE TITLE
Take screen for french wiki

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/QuestsDoc#25]
Hello, do you have a server with quests to install and the language in French where I could take screenshots to improve the wiki

![image](https://user-images.githubusercontent.com/74351200/186763672-53fa51bf-52ff-4392-913d-29f1ee43d9fb.png)

**Comment by PikaMug** [comment]
Many of the screenshots need to be updated (in English, too). I'll try to do this soon. Thanks!

**Comment by Beubeux74** [comment]
Okay, nice 😍

**Comment by PikaMug** [comment]
Screenshots have been updated. I've decided not to take any in French as doing this for every future language once a change is made would be a handful. The instructions use numbers (enter '1', selection '4', etc.) so it shouldn't be too confusing.
