### ISSUE TITLE
Add readme quests converter 

### ISSUE THREAD

**Issue by Beubeux74** [PikaMug/QuestsDoc#30]
Would it be possible to add at the end of the wiki the readme of _questsconverter_ so that the developers can use it directly ?
![image](https://user-images.githubusercontent.com/74351200/187288417-1007b512-5c2a-4d25-a906-f32e9bbbe150.png)
we could add a _questsconverter_ file and embed a notice in it
![image](https://user-images.githubusercontent.com/74351200/187288492-76483075-2b4c-48a0-97d3-01bf7a1f5aa1.png)

**Comment by PikaMug** [comment]
I'm not sure I understand what it is you're asking. Was there a particular page that you wanted more information about QuestsConverter on? And are you referring to software developers or server owners?

**Comment by Beubeux74** [comment]
No I just wanted to integrate this wiki directly into the quests wiki since it doesn't require a huge wiki
Like this for example
![image](https://user-images.githubusercontent.com/74351200/188954195-e9f84e5b-69fa-4e7f-b635-7a308f8ea02b.png)

**Comment by PikaMug** [comment]
I'm afraid a dedicated page would be outside the scope of this documentation, which is only meant to be about Quests. Briefly mentioning QuestsConverter on an existing page would be fine, though.
